export enum ScreenNames {
  // MainBottom
  Stacks = 'Stacks',
  Home = 'Home',
  Browse = 'Browse',
  Shop = 'Shop',
  Place = 'Place',
  //Stack
  Search = 'Search',
  Discount = 'Discount',
  DiscountDetail = 'DiscountDetail',
  ClaimDiscount = 'ClaimDiscount',
  SeeAllDeals = 'SeeAllDeals',
  // Settings
  Settings = 'Settings',
  EditProfileScreen = 'EditProfileScreen',
  ChangePasswordScreen = 'ChangePasswordScreen',
  HelpScreen = 'HelpScreen',
  PrivacyScreen = 'PrivacyScreen',
  SeeAllCollection = 'SeeAllCollection',
  CollectionDetail = 'CollectionDetail',
  CheckoutScreen = 'CheckoutScreen',
  Medicines = 'Medicines',
  DrugDetail = 'DrugDetail',
  SeeAllDrugs = 'SeeAllDrugs',
  DrugStores = 'DrugStores',
  PharmacyDetail = 'PharmacyDetail',
  Notification = 'Notification',
  MedicinePerscription = 'MedicinePerscription',
  NotificationDiscount = 'NotificationDiscount',
  Faq = 'Faq',
  //Browse
  SeeAllTrendingArticles = 'SeeAllTrendingArticles',
  SeeAllPopularArticles = 'SeeAllPopularArticles',
  ArticleDetail = 'ArticleDetail',
  EventDetail = 'EventDetail',
  SeeAllArticles = 'SeeAllArticles',
  // AuthStack
  AuthStack = 'AuthStack',
  WelcomeBack = 'WelcomeBack',
  CreateAccount = 'CreateAccount',
  ConfirmPhone = 'ConfirmPhone',
  CreatePassword = 'CreatePassword',
  AddEmail = 'AddEmail',
  AdditionalInformation = 'AdditionalInformation',
  ForgotPassword = 'ForgotPassword',
  ResetPassword = 'ResetPassword',
  LoginPage = 'LoginPage',
  //Shop
  SeeAllProductsScreen = 'SeeAllProductsScreen',
  ProductDetailScreen = 'ProductDetailScreen',
  StoresScreen = 'StoresScreen',
  BrandScreen = 'BrandScreen',
  // Place
  PlaceDetails = 'PlaceDetails',
  PlacePharmacyDetail = 'PlacePharmacyDetail',
}
