export enum ScreenNames {
  // MainBottom
  Browse = 'Browse',
  Shop = 'Shop',
  Place = 'Place',
  MainBottomTab = 'MainBottomTab',
  HomeStack = 'HomeStack',
  BrowseStack = 'BrowseStack',
  ShopStack = 'ShopStack',
  PlaceStack = 'PlaceStack',
  //HomeStack
  Home = 'Home',
  Search = 'Search',
  Discount = 'Discount',
  DiscountDetail = 'DiscountDetail',
  ClaimDiscount = 'ClaimDiscount',
  SeeAllDeals = 'SeeAllDeals',
  // Settings
  Settings = 'Settings',
  EditProfileScreen = 'EditProfileScreen',
  PasswordResetScreen = 'PasswordResetScreen',
  PhoneConfirmationScreen = 'PhoneConfirmationScreen',
  HelpScreen = 'HelpScreen',

  SeeAllCollection = 'SeeAllCollection',
  CollectionDetail = 'CollectionDetail',
  CheckoutScreen = 'CheckoutScreen',
  Medicines = 'Medicines',
  DrugDetail = 'DrugDetail',
  SeeAllDrugs = 'SeeAllDrugs',
  DrugStores = 'DrugStores',
  PharmacyDetail = 'PharmacyDetail',
  Notification = 'Notification',
  MedicinePerscription = 'MedicinePerscription',
  NotificationDiscount = 'NotificationDiscount',
  //Browse
  SeeAllTrendingArticles = 'SeeAllTrendingArticles',
  SeeAllPopularArticles = 'SeeAllPopularArticles',
  ArticleDetail = 'ArticleDetail',
  EventDetail = 'EventDetail',
  SeeAllArticles = 'SeeAllArticles',
  // AuthStack
  WelcomeBack = 'WelcomeBack',
  CreateAccount = 'CreateAccount',
  ConfirmPhone = 'ConfirmPhone',
  CreatePassword = 'CreatePassword',
  AddEmail = 'AddEmail',
  AdditionalInformation = 'AdditionalInformation',
  ForgotPassword = 'ForgotPassword',
  ResetPassword = 'ResetPassword',
  LoginPage = 'LoginPage',
  //Shop
  SeeAllProductsScreen = 'SeeAllProductsScreen',
  ProductDetailScreen = 'ProductDetailScreen',
  StoresScreen = 'StoresScreen',
  // Place
  PlaceDetails = 'PlaceDetails',
  PlacePharmacyDetail = 'PlacePharmacyDetail',
}
