export enum colors {
  primary = '#dccddc',
  secondary = '#f2f2f2',
  primaryTint = '#dccddc',
  secondaryTint = '#f2f2f2',
  gradient = '#dccddc',
  success = '#f2f2f2',
  warning = '#dccddc',
  error = '#f2f2f2',
  info = '#dccddc',
  neutral = '#f2f2f2',
  background = '#dccddc',
  text = '#f2f2f2',
  normal = '#f2f2f2',
}
