export const fonts = {
  display1: {fontFamily: 'Poppins-Black', fontSize: 64, color: 'black'},
  display2: {fontFamily: 'Poppins-ExtraBold', fontSize: 56, color: 'black'},
  heeding1: {fontFamily: 'Poppins-Bold', fontSize: 48, color: 'black'},
  heading2: {fontFamily: 'Poppins-Bold', fontSize: 40, color: 'black'},
  heading3: {fontFamily: 'Poppins-Bold', fontSize: 32, color: 'black'},
  heading4: {fontFamily: 'Poppins-Bold', fontSize: 28, color: 'black'},
  heading5: {fontFamily: 'Poppins-Bold', fontSize: 24, color: 'black'},
  heading6: {fontFamily: 'Poppins-Bold', fontSize: 20, color: 'black'},
  subtitle1: {fontFamily: 'Poppins-Medium', fontSize: 18, color: 'black'},
  subtitle2: {fontFamily: 'Poppins-Regular', fontSize: 16, color: 'black'},
  body: {fontFamily: 'Poppins-Regular', fontSize: 16, color: 'black'},
  body1: {fontFamily: 'Poppins-Regular', fontSize: 16, color: 'black'},
  body2: {fontFamily: 'Poppins-Regular', fontSize: 4, color: 'black'},
  button1: {fontFamily: 'Poppins-Medium', fontSize: 16, color: 'black'},
  button2: {fontFamily: 'Poppins-Regular', fontSize: 14, color: 'black'},
  caption: {fontFamily: 'Poppins-Regular', fontSize: 12, color: 'black'},
};
